server:
  port: 8081

spring:
  application:
    name: kafka-producer

#  kafka:
#    bootstrap-servers:
#      - localhost:10000
#      - localhost:10001
#      - localhost:10002
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.add.type.headers: false
